# Generated by Django 4.2.8 on 2024-03-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='labels',
        ),
        migrations.DeleteModel(
            name='Labels',
        ),
    ]
