# Generated by Django 4.2.8 on 2024-03-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_rename_primary_background_color_space_primary_bg_color_and_more'),
        ('boards', '0002_remove_board_labels_delete_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(default='#776bdc', max_length=7)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
            ],
            options={
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.AddField(
            model_name='board',
            name='labels',
            field=models.ManyToManyField(blank=True, to='boards.labels'),
        ),
    ]
