# Generated by Django 4.2.8 on 2024-03-28 17:44

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_labels_board_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='content',
        ),
        migrations.RemoveField(
            model_name='board',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.CharField(default=boards.models.generate_uuid, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labels',
            name='id',
            field=models.CharField(default=boards.models.generate_uuid, max_length=8, primary_key=True, serialize=False),
        ),
    ]
