# Generated by Django 4.2.8 on 2024-03-28 17:46

import boards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_remove_board_content_remove_board_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='id',
            field=models.CharField(default=boards.models.generate_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='labels',
            name='id',
            field=models.CharField(default=boards.models.generate_uuid, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
