# Generated by Django 4.2.8 on 2024-03-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_rename_primary_background_color_space_primary_bg_color_and_more'),
        ('boards', '0005_alter_board_id_alter_labels_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='author',
        ),
        migrations.AddField(
            model_name='board',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
    ]
