# Generated by Django 4.2.8 on 2024-03-28 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_rename_primary_background_color_space_primary_bg_color_and_more'),
        ('boards', '0006_remove_board_author_board_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
    ]
