# Generated by Django 4.2.8 on 2024-03-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_alter_board_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='labels',
        ),
    ]
