# Generated by Django 4.2.8 on 2024-03-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_space_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='slug',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
