# Generated by Django 4.2.8 on 2024-03-28 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_space_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='brand_color',
            field=models.CharField(default='#776bdc', max_length=7),
        ),
        migrations.AddField(
            model_name='space',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='space',
            name='primary_background_color',
            field=models.CharField(default='#171a1d', max_length=7),
        ),
        migrations.AddField(
            model_name='space',
            name='primary_text_color',
            field=models.CharField(default='#f5f5f5', max_length=7),
        ),
        migrations.AddField(
            model_name='space',
            name='secondary_background_color',
            field=models.CharField(default='#1d2025', max_length=7),
        ),
        migrations.AddField(
            model_name='space',
            name='secondary_text_color',
            field=models.CharField(default='#b3b3b3', max_length=7),
        ),
        migrations.AddField(
            model_name='spacemember',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
