# Generated by Django 4.2.8 on 2024-03-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_space_brand_color_space_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='primary_background_color',
            new_name='primary_bg_color',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='secondary_background_color',
            new_name='secondary_bg_color',
        ),
    ]
