# Generated by Django 4.2.8 on 2024-03-27 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_space_slug'),
        ('gamify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacerank',
            name='space',
        ),
        migrations.AddField(
            model_name='spacerank',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.spacemember'),
        ),
    ]
