# Generated by Django 4.2.8 on 2024-03-27 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0005_alter_spacerank_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacerank',
            name='user',
        ),
    ]
