# Generated by Django 4.2.8 on 2024-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0006_remove_spacerank_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalrank',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='spacerank',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
