# Generated by Django 4.2.8 on 2024-03-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0007_alter_globalrank_rank_alter_spacerank_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalrank',
            name='max_xp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='spacerank',
            name='max_xp',
            field=models.IntegerField(default=100),
        ),
    ]
