# Generated by Django 4.2.8 on 2024-03-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0008_alter_globalrank_max_xp_alter_spacerank_max_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalrank',
            old_name='rank',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='spacerank',
            old_name='rank',
            new_name='level',
        ),
    ]
