# Generated by Django 4.2.8 on 2024-01-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
