# Generated by Django 4.2.8 on 2024-03-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_onboarding_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='global_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='global_max_xp',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='global_xp',
            field=models.IntegerField(default=0),
        ),
    ]
