# Generated by Django 4.2.8 on 2024-03-27 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_global_level_profile_global_max_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='global_level',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='global_max_xp',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='global_xp',
        ),
    ]
