# Generated by Django 4.2.8 on 2024-03-28 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_global_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='onboarding_complete',
        ),
    ]
